Transform: AWS::Serverless-2016-10-31
Description: meme-type-chat sam app
Globals:
    Function:
        Timeout: 3
        Runtime: nodejs12.x

Resources:
    TelegramWebhookFunction:
        Type: AWS::Serverless::Function 
        Properties:
            CodeUri: src/
            Handler: app.telegramHandler
            Events:
                Telegram:
                    Type: Api
                    Properties:
                        Path: /telegram
                        Method: post
                        Auth:
                            ResourcePolicy:
                                IpRangeWhitelist:
                                - "149.154.160.0/20"
                                - "91.108.4.0/22"

